### ISSUE TITLE
Design: Attack/Spells Framework

### ISSUE THREAD

**Issue by menip** [Wpascuzzi/FAUST_Video_Game#2]
**Problem Description**
Cards (and enemies) need some way to apply their effects to units in the game. Ideally, this is done in a way that minimizes code duplication, and keeps the spell implementations separate from the card/unit performing the spell. 

There are two types of spells/effects: ones that resolve instantly, and ones that affect a unit or card for a greater period of time.

Examples of instant spells: deal 5 damage, deal 10 unblocked damage, instant kill, heal for 5.
Examples of spells modifying units: gain 50% dmg block, gain 75% outgoing dmg reduction, gain 1 bleed, gain 2 barrier for 5 turns.
Examples of spells modifying cards: permanently increase dmg by 2.
**Question:** Are there cards that modify units in this way? Can player be modified like this? Is players only defensive options to have cards in defensive slots?

**Solution**
[Command pattern](https://gameprogrammingpatterns.com/command.html) will be used to implement spell behavior. A spell must have know who is invoking it, and who the target is. Additional parameters optional: dmg dealt, block gained, etc. Spells can be made up multiple spells, to provide a framework of modular spells. For example, a card whose effect is to deal 5 dmg and gain 5 block would invoke two spells. If a card requires conditional effects, those are implemented in the spell itself. For example, a card that deals 5 dmg and 5 additional dmg if an enemy is below half hp would invoke the Damage spell and the LowHpDmg spell.

Spells that alter a unit for the rest of the battle will do so by modifying the units modifiers. A new class UnitModifiers will exist to store things such as unit dmg increase. CreatureModel will have an instance of this UnitModifiers class. This way, new modifiers can be added without modifying CreatureModel directly, and spells can know a unit will have this modifiers class. 
**Question:** What is the list of these unit modifiers?

Spells that alter a unit for x turns: two approach are possible here. If there is a standard set of buffs/debuffs that last for x turns, we could also have that be in UnitModifiers, with additional field for these de/buffs that specify x number of turns. A spell would then either set remaining duration, add to remaining duration, or clear remaining duration. Alternatively, we introduce a new class DeBuffs. This would store a spell and a number of turns that it should be active. CreatureModel would then have a list of DeBuffs, where at end of unit turn we iterate through that and resolve each de/buff: call the spell, lower remaining turns by one. A combined approach could also be an option. This way you could have a bleed effect that stays on a unit for x turns via UnitModifiers, and via Debuffs, a conditional spell on a unit that applies a bleed stack if the unit has too much barrier/armor. 

Spells that alter a card: likely the most straightforward approach would be to have the card itself take care of modifying itself. For things like increase dmg permanently upon playing this would work. For cards that deal more dmg for x card in your deck, would probs be able to query some class like Deck.GetNumCardsWithTitle(...) for this info. 
**Question:** What is the list of card modifiers planned? Are there cards planned that can modify other cards? For example, when card A is played, all cards B get more dmg, or can't be played, or something like this

**Comment by Wpascuzzi** [comment]
Regarding unit/card modifiers, I think we have an abstract ModifierModel class that is inherited by abstract UnitModifier/CardModifier classes, and then finally each specific modifier is a sealed class describing its behavior.

Modifier model might have something like
```
- Buff vs Debuff
- Stackability
	- Not Possible
	- Stacks on same buff
	- Stacks uniquely
	
-Removable?

Each modifier needs to implement a method that explains how it applies
"A buff is responsible for how it is added to the target"
```

**Comment by Wpascuzzi** [comment]
Going forward, for language clarity, we'll call what you've been referring to as "spells" here as "Actions"

**Comment by Wpascuzzi** [comment]
We discussed modifiers that can potentially affect other modifiers. For now a simple to intuit implementation is to iterate through the existing modifiers contained on a unit to see if any should affect newly added modifiers. Also, these "modifier modifiers" are should probably not be allowed to permanently alter existing modifiers on the unit, in case the modifier is removed

Probably a given modifier will have a list of references to modifiers that affect it, and will use that in making any calculations.

Modifiers will likely need a priority number to determine which order they are applied or are used in a calculation.

**Comment by Wpascuzzi** [comment]
I want us to have interfaces for specific types of modifiers. 

For example a IDamageModifier
and a DamageDoublerBuff

DamageDoublerBuff would inherit from Unitmodifiers, and implement IDamageModifier. This would allow us to be certain that DamageDoubler has a function like "modifyDamage" which we can have the unit pass the base damage of a card into whenever calculating the damage it does.
